### PR TITLE
Conditional reference series triple record

### PR DESCRIPTION
**Pull request by nedmsmith**
Added conditional-reference-series-triples extension with test case.

### CODE REVIEW

**Comment by nedmsmith** [comment]
Is it OK to merge this PR?

**Comment by thomas-fossati** [comment]
> Is it OK to merge this PR?

The CDDL looks good, but I am slightly confused by the lack of accompanying prose in the draft.  I thought this was a "draft PR" rather than one ready to ship.

**Comment by nedmsmith** [comment]
>> Is it OK to merge this PR?
> 
> The CDDL looks good, but I am slightly confused by the lack of accompanying prose in the draft. I thought this was a "draft PR" rather than one ready to ship.

This PR is only aimed at the CDDL another PR is needed that includes prose for the I-D.

**Comment by thomas-fossati** [comment]
> This PR is only aimed at the CDDL another PR is needed that includes prose for the I-D.

The subsequent PR will need to also change (slightly) the content of this one, in order to comply with the presentation style of the document.

**Comment by nedmsmith** [comment]
> The subsequent PR will need to also change (slightly) the content of this one, in order to comply with the presentation style of the document.



> > This PR is only aimed at the CDDL another PR is needed that includes prose for the I-D.
> 
> The subsequent PR will need to also change (slightly) the content of this one, in order to comply with the presentation style of the document.

Can you suggest how it will be changed and where in the I-D the prose should appear?

**Comment by henkbirkholz** [comment]
it's a compromise. not great, but not a blocker

**Pull request merged**
