### PR TITLE
BEST PR EVER: allow one measurement-map only in RVs and EVs

### PR DESCRIPTION
**Pull request by thomas-fossati**
As discussed in our call today.

Signed-off-by: Thomas Fossati <thomas.fossati@arm.com>

### CODE REVIEW

**Comment by yogeshbdeshpande** [comment]
_BEST PR EVER to review:_

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!

**Review by nedmsmith — APPROVED** [review]

**Comment by nedmsmith** [comment]
Copying misdirected conversation from PR #25:

In the example cbor diag below from (https://github.com/ietf-rats-wg/draft-ietf-rats-corim/blob/main/cddl/examples/comid-1.diag), the array at / measurement-map / [ { and at the end } ] should be removed since the array was removed from the triple definition.

},
      / measurement-map / [ {
        / comid.mval / 1 : {
          / comid.ver / 0 : {
            / comid.version / 0 : "1.0.0",
            / comid.version-scheme / 1 : 16384 / semver /
          },
          / comid.digests / 2 : [ [
            / hash-alg-id / 1, / sha256 /
            / hash-value / h'44aa336af4cb14a879432e53dd6571c7fa9bccafb75f488259262d6ea3a4d91b'
          ] ]
        }
      } ]

**Comment by thomas-fossati** [comment]
> Copying misdirected conversation from PR #25:
> 
> In the example cbor diag below from (https://github.com/ietf-rats-wg/draft-ietf-rats-corim/blob/main/cddl/examples/comid-1.diag), the array at `/ measurement-map / [ {` and at the end `} ]` should be removed since the array was removed from the triple definition.
> 
> ```
> },
>       / measurement-map / [ {
>         / comid.mval / 1 : {
>           / comid.ver / 0 : {
>             / comid.version / 0 : "1.0.0",
>             / comid.version-scheme / 1 : 16384 / semver /
>           },
>           / comid.digests / 2 : [ [
>             / hash-alg-id / 1, / sha256 /
>             / hash-value / h'44aa336af4cb14a879432e53dd6571c7fa9bccafb75f488259262d6ea3a4d91b'
>           ] ]
>         }
>       } ]
> ```

spot on!

**Pull request merged**
