### PR TITLE
Remove appendices describing evidence translation

### PR DESCRIPTION
**Pull request by nedmsmith**
removed evidence translation appendices and references to these sections.
They can now be found in: https://github.com/ietf-rats-wg/draft-smith-rats-evidence-trans

### CODE REVIEW

**Comment by nedmsmith** [comment]
This addresses issue #240

**Review by deeglaze — APPROVED** [review]

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!

**Review by thomas-fossati — APPROVED** [review]
Looks excellent to me :-)

**Review by henkbirkholz — APPROVED** [review]
lgtm (including local tool chain)

**Pull request merged**
