### PR TITLE
First initial Proposal for adding multiple measurement maps to a Reference Triple

### PR DESCRIPTION
**Pull request by yogeshbdeshpande**
[WIP] Multiple Measurements in a Reference Triple

### CODE REVIEW

**Comment by yogeshbdeshpande** [comment]
I will update examples for the PR to compile properly, once we have evaluated the `impact`

**Comment by henkbirkholz** [comment]
Are we revisiting this topic? If my memory does not fail me, didn't we go for "only one object in the triple" choosing simplicity over conciseness in this case?

**Comment by yogeshbdeshpande** [comment]
> Are we revisiting this topic? If my memory does not fail me, didn't we go for "only one object in the triple" choosing simplicity over conciseness in this case?

`Yes` we are revisiting this topic. I believe this will be beneficial, as many use cases exists today where this change will help the users of the specification.

**Comment by yogeshbdeshpande** [comment]
Closing this PR as the alternative proposal is progressed via discussions on 
https://github.com/ietf-rats-wg/draft-ietf-rats-corim/pull/189

**Comment by deeglaze** [comment]
We're revisiting this as of 2024-08-14 so we can account for single evidence objects that measure multiple things, each with data type representations that fit with the standard codepoints in measurement-values-map.

The mkey use for "subcomponents" I think needs environment-map representation. There are different requirements here. Any inclusion of mkey should come with measurement-map multiplicity. If there's any multiplicity, then every element must have an mkey value, and they must be distinct.

**Comment by yogeshbdeshpande** [comment]
Addressed by PR#257

**Pull request closed without merging**
